// Sam Garvis

#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "./images/runningman.h"
#include "./images/stopsign.h"
#include "./images/prettyroad.h"
#include "./images/loseGame.h"
#include "./images/wingame.h"
// #include "code.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PREPARE_GAME,
  PLAY,
  WIN,
  LOSE,
} GBAState;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  // This loads the current and previous states. This is need to update the new state
  // while still having the old state to undraw it.
  GameLive currGameLive, newGameLive;

  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // if the backspace is selected then return to the main screen.
    // this is need at the beginning of the loop so every state can reach this
    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
    }

    switch (state) {
      case START:
        waitForVBlank();

        // initilize the home screen
        drawFullScreenImageDMA(prettyroad);
        drawRectDMA(87,100, 67,10,CYAN);
        drawString(101, 87, "Press Enter", RED);

        // if enter is pressed then go to the beginning of the game
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
            state = PREPARE_GAME;
        }
        break;


      case PREPARE_GAME:
        waitForVBlank();

        // draw the beginning of the game
        fillScreenDMA(GREEN);
        startGame(&currGameLive);
        drawFirstGameState(&currGameLive);
        state = PLAY;
        break;

      case PLAY:
        // update the game and move the objects around as such
        newGameLive = updateGame(&currGameLive, currentButtons);

        waitForVBlank();

        undrawGameState(&currGameLive);
        drawSecondGameState(&newGameLive);

        // put the updated state into the previous state
        currGameLive = newGameLive;
        // if the player has 0 lives left go to LOSE state
        if (currGameLive.dead == 1) {
          state = LOSE;
        }
        // if the player reached the far edge go to WIN state
        if (currGameLive.win == 1) {
          state = WIN;
        }
        break;

      case WIN:
        waitForVBlank();

        // draw the winning screen
        drawFullScreenImageDMA(wingame);
        drawRectDMA(87,125,59,10,CYAN);
        drawString(126, 87, "YOU WON :)", WHITE);
        // state = ?
        break;
      case LOSE:
        waitForVBlank();

        // draw the losing screen
        drawFullScreenImageDMA(loseGame);
        drawRectDMA(160,100,66,10,CYAN);
        drawString(101, 160, "YOU LOST :(", RED);
        // state = ?
        break;
    }
  }

  return 0;
}
